version: "1"

services:   
  mongo1:
    image: mongo:5.0.2
    container_name: database-mongodb-1
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=unu2024dos
    ports:  
      - 27018:27017
    networks:
      - grupo3 

  mongo2:
    image: mongo:5.0.2
    container_name: database-mongodb-2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=unu2024dos
    ports:  
      - 27019:27017
    networks:
      - grupo3

networks:
  grupo3:
    name: ms-grupo3