version: "1"

services:
  postgres:
    image: postgres:alpine3.14
    container_name: database-postgres
    restart: always
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=proyectoGrupo3
    ports:
    - 5433:5432
    networks:
    - td2023
    
networks:
  td2023:
    name: ms-tdg

