version: "1"

services:
   sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: database-sql-server
    restart: always
    ports:
    - 1434:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Admin@2024Secure
    networks:
    - grupo3
    
networks:
  grupo3:
    name: ms-grupo3

