version: "1"

services:
  mysql:
    image: mysql:8.0.26
    container_name: db-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=unu2024dos
    ports:
    - 3308:3306
    - 33062:33060
    networks:
    - grupo3
    
networks:
  grupo3:
    name: ms-grupo3

